#
# default: https://github.com/alacritty/alacritty/blob/master/alacritty.yml
#

env:
  TERM: xterm-256color

window:
  dimensions:
    columns: 160
    lines  : 85
  padding:
    x: 7
    y: 7

font:
  normal:
    family: 'HackGen Console NF'
    style : Regular
  bold:
    family: 'HackGen Console NF'
    style : Bold
  italic:
    family: 'HackGen Console NF'
    style : Italic
  bold_italic:
    family: 'HackGen Console NF'
    style : Bold Italic
  size: 14.0

mouse_bindings:
  - { mouse: Right , action: PasteSelection }
  - { mouse: Middle, action: Copy           }

